parameters:
  # Data ETL & Feature engineering pipelines parameters
  author_links: 
    - user_full_name: Maxime Labonne # [First Name(s)] [Last Name]
      links:
        # Substack
        - https://maximelabonne.substack.com/p/uncensor-any-llm-with-abliteration-d30148b7d43e
        - https://maximelabonne.substack.com/p/create-mixtures-of-experts-with-mergekit-11b318c99562