name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  qa:
    name: qa
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version-file: ".python-version"
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.6.0"
      
      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: gitleaks check
        run: uv run poe gitleaks-check
      
      - name: Lint check [Python]
        run: uv run poe lint-check
      
      - name: Format check [Python]
        run: uv run poe format-check